language: swift
osx_image: xcode11.2
os: osx
xcode_sdk: iphonesimulator13.2.2

branches:
  only:
  - master

before_script:
  - ./CK_Example/Pods/SwiftLint/swiftlint lint --config .swiftlint-ci.yml;

jobs:
  include:
    - stage: Unit Tests & Deploy
      name: 'Library Unit Tests'
      env: 
        - CI_BUILD_TARGET='CascadeKit'
        - OS='13.2.2'
      script: travis/UnitTest.sh
