language: swift
osx_image: xcode10
os: osx

branches:
  only:
  - master

before_script:
  - bundle install
  - ./CK_Example/Pods/SwiftLint/swiftlint lint --config .swiftlint-ci.yml;

jobs:
  include:
    - stage: Unit Tests & Deploy
      name: 'Library Unit Tests"
      env: 
        - CI_BUILD_TARGET='CascadeKit'
        - OS='12.0'
      script: travis/UnitTest.sh
