language: swift
osx_image: xcode10
os: osx

branches:
  only:
  - master

before_script:
  - bundle install
  #- bundle exec danger
  - ./CK_Example/Pods/SwiftLint/swiftlint lint --config .swiftlint-ci.yml;

jobs:
  include:
    - stage: Unit Tests & Deploy
      name: 'Library Unit Tests (iPhone 11 Pro Max, iOS 13.2.2)'
      env: 
        - CI_BUILD_TARGET='CascadeKit'
        - OS='13.2.2'
      script: travis/UnitTest.sh